In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Téléchargement des données

## Données conso :

Les données sont téléchargées sur : <br/>
https://www.rte-france.com/fr/eco2mix/eco2mix-telechargement

In [39]:
data = pd.read_excel("data.xlsx")
data.head()

,Mois,Qualité,Territoire,Production totale,Production nucléaire,Production thermique totale,Production thermique charbon,Production thermique fioul,Production thermique gaz,Production hydraulique,...,Production bio-énergies,Consommation totale,Solde exportateur,Echanges export,Echanges import,Echanges avec le Royaume-uni,Echanges avec l'Espagne,Echanges avec l'Italie,Echanges aves la Suisse,Echanges avec l'Allemagne et la Belgique
0,0000-00,Données consolidées,Grand-Est,7296,5505.0,864,153.0,8,701,537,...,70,3364,3876.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000-00,Données définitives,Nouvelle-Aquitaine,4523,3740.0,26,NaN,9,16,162,...,131,3222,1300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0000-00,Données définitives,Auvergne-Rhône-Alpes,8890,5946.0,32,4.0,17,10,2632,...,79,5010,3658.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0000-00,Données définitives,Bourgogne-Franche-Comté,152,NaN,19,0.0,0,19,19,...,20,1533,-1383.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0000-00,Données définitives,Bretagne,197,NaN,3,NaN,3,0,46,...,37,1493,-1300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 22 columns):
Mois                                        1037 non-null object
Qualité                                     1037 non-null object
Territoire                                  1037 non-null object
Production totale                           1037 non-null int64
Production nucléaire                        652 non-null float64
Production thermique totale                 1037 non-null int64
Production thermique charbon                714 non-null float64
Production thermique fioul                  1037 non-null int64
Production thermique gaz                    1037 non-null int64
Production hydraulique                      1037 non-null int64
Production éolien                           1037 non-null int64
Production solaire                          1037 non-null int64
Production bio-énergies                     1037 non-null int64
Consommation totale                         1037 non-null int64
Solde exportateur                           953 non-null float64
Echanges export                             113 non-null float64
Echanges import                             113 non-null float64
Echanges avec le Royaume-uni                113 non-null float64
Echanges avec l'Espagne                     113 non-null float64
Echanges avec l'Italie                      113 non-null float64
Echanges aves la Suisse                     113 non-null float64
Echanges avec l'Allemagne et la Belgique    113 non-null float64
dtypes: float64(10), int64(9), object(3)
memory usage: 178.3+ KB

In [44]:
#Afin de coller avec les données DJU nous allons concentrer l'étude sur une région, et nous ne gardons que 
#Les données définitives.
conso = data.loc[data['Territoire'] == 'Auvergne-Rhône-Alpes']
conso = conso.loc[conso['Qualité'] == 'Données définitives']

#Les colonnes qui nous intéressent désormais sont la date et la conso : 
conso = conso[['Mois', 'Consommation totale']]

#Pas de données avant Janvier 2014, on enlève donc les mois précédents : 
conso = conso.loc[conso['Mois'] > "2013-12"]

#Les données DJU vont jusqu'au 05/2018 :
conso = conso.loc[conso['Mois'] < "2019-01"]

#On renomme les colonnes : 
conso = conso.rename(columns={'Mois':'date', 'Consommation totale':'consommation'})

## Données DJU

Données téléchargées sur : <br/>
https://cegibat.grdf.fr/simulateur/calcul-dju